spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cv
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    enabled: true
  application:
    name: CVHoster
server:
  port: 8081
