spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    enabled: true
  application:
    name: CandidateManagement
server:
  port: 8080
